version: "3.1"
volumes:
  minio_data: null

services:

  minio:
    image: minio/minio
    volumes:
      - "minio_data:/data"
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    command: "--compat server /data"
    ports:
      - "9000:9000"
